//
// auto-generated by ops.py
//
#include "./OpenACC/wave_common.h"

#define OPS_GPU

int xdim0_wave_block0_2_kernel;
int xdim1_wave_block0_2_kernel;
int xdim2_wave_block0_2_kernel;


#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2


#define OPS_ACC0(x) (x)
#define OPS_ACC1(x) (x)
#define OPS_ACC2(x) (x)

//user function
inline
void wave_block0_2_kernel(const double *wk1 , const double *phi_old , double *phi , const double *rknew)
{
phi[OPS_ACC2(0)] = deltat*rknew[0]*wk1[OPS_ACC0(0)] + phi_old[OPS_ACC1(0)];
}


#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2



void wave_block0_2_kernel_c_wrapper(
  double *p_a0,
  double *p_a1,
  double *p_a2,
  double p_a3,
  int x_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1,p_a2)
  #pragma acc loop
  #endif
  for ( int n_x=0; n_x<x_size; n_x++ ){
    wave_block0_2_kernel(  p_a0 + n_x*1*1,
           p_a1 + n_x*1*1, p_a2 + n_x*1*1,
           &p_a3 );

  }
}
