//
// auto-generated by ops.py
//
#include "./OpenACC/wave_common.h"

#define OPS_GPU

int xdim0_wave_block0_0_kernel;
int xdim1_wave_block0_0_kernel;


#undef OPS_ACC0
#undef OPS_ACC1


#define OPS_ACC0(x) (x)
#define OPS_ACC1(x) (x)

//user function
inline
void wave_block0_0_kernel(const double *phi , double *wk0)
{
wk0[OPS_ACC1(0)] = ((rc0)*phi[OPS_ACC0(-4)] - rc1*phi[OPS_ACC0(-3)] + (rc2)*phi[OPS_ACC0(-2)] - rc3*phi[OPS_ACC0(-1)] + (rc3)*phi[OPS_ACC0(1)] - rc2*phi[OPS_ACC0(2)] + (rc1)*phi[OPS_ACC0(3)] - rc0*phi[OPS_ACC0(4)])/deltai0;
}


#undef OPS_ACC0
#undef OPS_ACC1



void wave_block0_0_kernel_c_wrapper(
  double *p_a0,
  double *p_a1,
  int x_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1)
  #pragma acc loop
  #endif
  for ( int n_x=0; n_x<x_size; n_x++ ){
    wave_block0_0_kernel(  p_a0 + n_x*1*1,
           p_a1 + n_x*1*1 );

  }
}
