//
// auto-generated by ops.py
//
#include "./OpenACC/wave_common.h"

#define OPS_GPU

int xdim0_wave_block0_1_kernel;
int xdim1_wave_block0_1_kernel;


#undef OPS_ACC0
#undef OPS_ACC1


#define OPS_ACC0(x) (x)
#define OPS_ACC1(x) (x)

//user function
inline
void wave_block0_1_kernel(const double *wk0 , double *wk1)
{
wk1[OPS_ACC1(0)] = -c0*wk0[OPS_ACC0(0)];
}


#undef OPS_ACC0
#undef OPS_ACC1



void wave_block0_1_kernel_c_wrapper(
  double *p_a0,
  double *p_a1,
  int x_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1)
  #pragma acc loop
  #endif
  for ( int n_x=0; n_x<x_size; n_x++ ){
    wave_block0_1_kernel(  p_a0 + n_x*1*1,
           p_a1 + n_x*1*1 );

  }
}
