//
// auto-generated by ops.py
//
#include "./OpenACC/wave_common.h"

#define OPS_GPU

int xdim0_wave_block0_5_kernel;


#undef OPS_ACC0


#define OPS_ACC0(x) (x)

//user function
inline
void wave_block0_5_kernel(double *phi , const int *idx)
{
phi[OPS_ACC0(0)] = sin(2*deltai0*idx[0]*M_PI);
}


#undef OPS_ACC0



void wave_block0_5_kernel_c_wrapper(
  double *p_a0,
  int *p_a1,
  int arg_idx0,
  int x_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0)
  #pragma acc loop
  #endif
  for ( int n_x=0; n_x<x_size; n_x++ ){
    int arg_idx[] = {arg_idx0+n_x};
    wave_block0_5_kernel(  p_a0 + n_x*1*1,
          arg_idx );

  }
}
