//
// auto-generated by ops.py//

#include "./OpenACC/wave_common.h"


void ops_decl_const_char(int dim, char const *type,
int size, char *dat, char const *name){
  if (!strcmp(name,"rc1")) {
    rc1 = *(double*)dat;
  }
  else
  if (!strcmp(name,"rc2")) {
    rc2 = *(double*)dat;
  }
  else
  if (!strcmp(name,"rc0")) {
    rc0 = *(double*)dat;
  }
  else
  if (!strcmp(name,"deltat")) {
    deltat = *(double*)dat;
  }
  else
  if (!strcmp(name,"c0")) {
    c0 = *(double*)dat;
  }
  else
  if (!strcmp(name,"deltai0")) {
    deltai0 = *(double*)dat;
  }
  else
  if (!strcmp(name,"rc3")) {
    rc3 = *(double*)dat;
  }
  else
  if (!strcmp(name,"nx0")) {
    nx0 = *(int*)dat;
  }
  else
  {
    printf("error: unknown const name\n"); exit(1);
  }
}
