//
// auto-generated by ops.py
//
#include "./OpenACC/wave_common.h"

#define OPS_GPU

int xdim0_wave_block0_3_kernel;
int xdim1_wave_block0_3_kernel;


#undef OPS_ACC0
#undef OPS_ACC1


#define OPS_ACC0(x) (x)
#define OPS_ACC1(x) (x)

//user function
inline
void wave_block0_3_kernel(const double *wk1 , double *phi_old , const double *rkold)
{
phi_old[OPS_ACC1(0)] = deltat*rkold[0]*wk1[OPS_ACC0(0)] + phi_old[OPS_ACC1(0)];
}


#undef OPS_ACC0
#undef OPS_ACC1



void wave_block0_3_kernel_c_wrapper(
  double *p_a0,
  double *p_a1,
  double p_a2,
  int x_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1)
  #pragma acc loop
  #endif
  for ( int n_x=0; n_x<x_size; n_x++ ){
    wave_block0_3_kernel(  p_a0 + n_x*1*1,
           p_a1 + n_x*1*1, &p_a2 );

  }
}
