//
// auto-generated by ops.py
//
//header
#define OPS_ACC_MD_MACROS
#ifdef __cplusplus
#include "ops_lib_cpp.h"
#endif
#ifdef OPS_MPI
#include "ops_mpi_core.h"
#endif
#include "ops_cuda_rt_support.h"

// global constants
extern double rc1;
extern double rc2;
extern double rc0;
extern double deltat;
extern double c0;
extern double deltai0;
extern double rc3;
extern int nx0;
