//
// auto-generated by ops.py
//
#include "./MPI_inline/wave_common.h"

int xdim0_wave_block0_1_kernel;
int xdim1_wave_block0_1_kernel;

#define OPS_ACC0(x) (n_x*1+x)
#define OPS_ACC1(x) (n_x*1+x)

//user function



void wave_block0_1_kernel_c_wrapper(
  const double * restrict wk0,
  double * restrict wk1,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    
wk1[OPS_ACC1(0)] = -c0*wk0[OPS_ACC0(0)];

  }
}
#undef OPS_ACC0
#undef OPS_ACC1

