//
// auto-generated by ops.py
//
#include "./MPI_inline/wave_common.h"

int xdim0_wave_block0_0_kernel;
int xdim1_wave_block0_0_kernel;

#define OPS_ACC0(x) (n_x*1+x)
#define OPS_ACC1(x) (n_x*1+x)

//user function



void wave_block0_0_kernel_c_wrapper(
  const double * restrict phi,
  double * restrict wk0,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    
wk0[OPS_ACC1(0)] = ((rc0)*phi[OPS_ACC0(-4)] - rc1*phi[OPS_ACC0(-3)] + (rc2)*phi[OPS_ACC0(-2)] - rc3*phi[OPS_ACC0(-1)] + (rc3)*phi[OPS_ACC0(1)] - rc2*phi[OPS_ACC0(2)] + (rc1)*phi[OPS_ACC0(3)] - rc0*phi[OPS_ACC0(4)])/deltai0;

  }
}
#undef OPS_ACC0
#undef OPS_ACC1

