//
// auto-generated by ops.py
//
#include "./MPI_inline/wave_common.h"

int xdim0_wave_block0_4_kernel;
int xdim1_wave_block0_4_kernel;

#define OPS_ACC0(x) (n_x*1+x)
#define OPS_ACC1(x) (n_x*1+x)

//user function



void wave_block0_4_kernel_c_wrapper(
  const double * restrict phi,
  double * restrict phi_old,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    
phi_old[OPS_ACC1(0)] = phi[OPS_ACC0(0)];

  }
}
#undef OPS_ACC0
#undef OPS_ACC1

