//
// auto-generated by ops.py
//
#include "./MPI_inline/wave_common.h"

int xdim0_wave_block0_2_kernel;
int xdim1_wave_block0_2_kernel;
int xdim2_wave_block0_2_kernel;

#define OPS_ACC0(x) (n_x*1+x)
#define OPS_ACC1(x) (n_x*1+x)
#define OPS_ACC2(x) (n_x*1+x)

//user function



void wave_block0_2_kernel_c_wrapper(
  const double * restrict wk1,
  const double * restrict phi_old,
  double * restrict phi,
  const double * restrict rknew,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    
phi[OPS_ACC2(0)] = deltat*rknew[0]*wk1[OPS_ACC0(0)] + phi_old[OPS_ACC1(0)];

  }
}
#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2

