//
// auto-generated by ops.py
//
#include "./MPI_inline/wave_common.h"

int xdim0_wave_block0_5_kernel;

#define OPS_ACC0(x) (n_x*1+x)

//user function



void wave_block0_5_kernel_c_wrapper(
  double * restrict phi,
  int * restrict idx,
  int arg_idx0, 
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    int idx[] = {arg_idx0+n_x};
    
phi[OPS_ACC0(0)] = sin(2*deltai0*idx[0]*M_PI);

  }
}
#undef OPS_ACC0

