//
// auto-generated by ops.py//

//header
#define OPS_ACC_MD_MACROS
#include "ops_lib_cpp.h"
#ifdef OPS_MPI
#include "ops_mpi_core.h"
#endif

//set max number of OMP threads for reductions
#ifndef MAX_REDUCT_THREADS
#define MAX_REDUCT_THREADS 64
#endif
//global constants
extern double rc1;
extern double rc2;
extern double rc0;
extern double deltat;
extern double c0;
extern double deltai0;
extern double rc3;
extern int nx0;

//user kernel files
#include "wave_block0_5_kernel_omp_kernel.cpp"
#include "wave_block0_4_kernel_omp_kernel.cpp"
#include "wave_block0_0_kernel_omp_kernel.cpp"
#include "wave_block0_1_kernel_omp_kernel.cpp"
#include "wave_block0_2_kernel_omp_kernel.cpp"
#include "wave_block0_3_kernel_omp_kernel.cpp"
